Changed from NymN reddit to forsen reddit
hotbear1110/botbear pull request #73
Opened 2023-01-21 23:26 UTC by mynamecheff

2023-01-21 23:34 UTC, JoachimFlottorp requested changes

2023-01-21 23:34 UTC, JoachimFlottorp commented on commands/Reddit.js
> +      const posts = response.body.data.children;
this should just be response.data.children

2023-01-21 23:34 UTC, JoachimFlottorp commented on commands/Reddit.js
> +      const response = await got('https://www.reddit.com/r/RedditAndChill/.json', { json: true });
Change this from got(..., { json: true })

To got(...).json();

2023-01-21 23:34 UTC, JoachimFlottorp commented on commands/Reddit.js
> +      return top3.join('\n');
Twitch doesn't allow newlines.

2023-02-08 12:36 UTC, hotbear1110 commented
If possible, links to the posts would maybe be nice to have

2023-02-08 12:38 UTC, hotbear1110 approved these changes
seemsgood

2023-02-08 12:38 UTC, hotbear1110 commented on commands/Reddit.js
> +  name: 'Reddit',
I would like this to be lowercase, same with the filename

2023-02-08 12:38 UTC, hotbear1110 commented on commands/Reddit.js
> +  description: 'This command will list the top 3 posts on the Forsen subreddit.',
This still says forsen

2023-02-08 22:04 UTC, merged